### ISSUE TITLE
"reproduce an error hit overnight by OSS-Fuzz" feels incomplete

### ISSUE THREAD

**Issue by bagder** [curl/curl-fuzzer#10]
Hi.

I wanted to once and for all get my act together and be able to repro OSS-Fuzz problems myself. I follow the guide to repro a OSS-Fuzz problem and the README.db directs me to https://github.com/google/oss-fuzz. But then I'm left stranded. What am I looking for there? I'm lost. Maybe the README can be a little more elaborate?

**Comment by cmeister2** [comment]
Hmm. Probably could be a bit more helpful here.

In order to _precisely_ replicate the environment used by Google OSS-Fuzz, it's true that running OSS-Fuzz is helpful.

I would say that by far the easiest way of reproducing a test case failure is to try running the mainline.sh script locally, and using the appropriate binary generated to try the test case.

I'll try and make an update shortly which says this.

**Comment by cmeister2** [comment]
@bagder: have added a `REPRODUCING.md` file which should go into a bit more detail about how to diagnose these issues. Would you be able to review and let me know if you need more detail in any areas?
