### ISSUE TITLE
Coverage is much much lower without threaded resolution

### ISSUE THREAD

**Issue by cmeister2** [curl/curl-fuzzer#7]
Disabling threaded resolution causes coverage to drop significantly.

By disabling threaded resolution we have to call Curl_resolv_timeout, which uses an alarm() based timeout mechanism. Because our configured timeout of 200ms is less than 1000ms (alarm() uses integers for timeouts), we fail.

There are two potential fixes:

- Re-enable threaded resolution: this ought to fix up the overnights for now.
- Disable resolution of names because it's not really necessary: I have no idea how much work this will be, but there's no need for curl to resolve names if we're going to ignore it and open the socket function anyway. This might require a fix in the curl project.

@bagder: any thoughts on this? You previously mentioned that us resolving names may indicate a bug.

**Comment by jay** [comment]
Which timeout is the problem, and in curl-fuzzer or curl project? If it's the former couldn't you just configure the timer for some longer value, what is the disadvantage to doing that? I think though since threaded resolver is now the default for autotools it would make sense to test threaded resolver. OTOH I seem to have some faint memory from years ago of having to disable threaded resolver in Ubuntu for better make test coverage, probably something to do with memory logging.

**Comment by cmeister2** [comment]
The timer is a CURLOPT, CURLOPT_TIMEOUT_MS. The fuzzer sets it to 200ms. In an ideal world we would not ever get anywhere near this timeout - the point of the fuzzer is to do lots and lots of testcases very very fast. Configuring a longer value will likely be detrimental to fuzzer performance. I could try turning it off to see if we actually run into any problems.

OTOH I'm happy to have a default of "threaded resolver" :smile:

**Comment by cmeister2** [comment]
None of the existing test cases appears to hit timeouts when turning off TIMEOUT, which is promising. I'll create a branch and throw oss-fuzz at it for a bit to see if it hits any obvious timeouts.

**Comment by jay** [comment]
I see. What you probably meant to say is alarm uses _seconds_ for timeouts, re
https://github.com/curl/curl/blob/curl-7_56_0/lib/hostip.c#L605-L612
You could also try setting it to 1000 to see what happens. More interesting though is why it's happening in the first place and what it's looking up. We occasionally get weird CI errors on the curl project where things will just randomly timeout in travis builds, and they don't seem to be related to curl. In other words I think sometimes the instance just slows down so much it is unusable, so that could explain a timeout.

**Comment by cmeister2** [comment]
I went with the threaded resolver for now. I may return to this later.
